// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_detector.proto

package devicepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type StringRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringRequest) Reset()         { *m = StringRequest{} }
func (m *StringRequest) String() string { return proto.CompactTextString(m) }
func (*StringRequest) ProtoMessage()    {}
func (*StringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{0}
}

func (m *StringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringRequest.Unmarshal(m, b)
}
func (m *StringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringRequest.Marshal(b, m, deterministic)
}
func (m *StringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringRequest.Merge(m, src)
}
func (m *StringRequest) XXX_Size() int {
	return xxx_messageInfo_StringRequest.Size(m)
}
func (m *StringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StringRequest proto.InternalMessageInfo

func (m *StringRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// The request message containing the user's name.
type BleRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Distance             float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BleRequest) Reset()         { *m = BleRequest{} }
func (m *BleRequest) String() string { return proto.CompactTextString(m) }
func (*BleRequest) ProtoMessage()    {}
func (*BleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{1}
}

func (m *BleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BleRequest.Unmarshal(m, b)
}
func (m *BleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BleRequest.Marshal(b, m, deterministic)
}
func (m *BleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BleRequest.Merge(m, src)
}
func (m *BleRequest) XXX_Size() int {
	return xxx_messageInfo_BleRequest.Size(m)
}
func (m *BleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BleRequest proto.InternalMessageInfo

func (m *BleRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BleRequest) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *BleRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type ReporterAddressRequest struct {
	Agent                *Agent            `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Addresses            []*AddressRequest `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata             []*Metadata       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReporterAddressRequest) Reset()         { *m = ReporterAddressRequest{} }
func (m *ReporterAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ReporterAddressRequest) ProtoMessage()    {}
func (*ReporterAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{2}
}

func (m *ReporterAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReporterAddressRequest.Unmarshal(m, b)
}
func (m *ReporterAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReporterAddressRequest.Marshal(b, m, deterministic)
}
func (m *ReporterAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterAddressRequest.Merge(m, src)
}
func (m *ReporterAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ReporterAddressRequest.Size(m)
}
func (m *ReporterAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterAddressRequest proto.InternalMessageInfo

func (m *ReporterAddressRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *ReporterAddressRequest) GetAddresses() []*AddressRequest {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ReporterAddressRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReporterAddressRequest) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReporterBleRequest struct {
	Agent                *Agent      `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Bles                 *BleRequest `protobuf:"bytes,2,opt,name=bles,proto3" json:"bles,omitempty"`
	Metadata             []*Metadata `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReporterBleRequest) Reset()         { *m = ReporterBleRequest{} }
func (m *ReporterBleRequest) String() string { return proto.CompactTextString(m) }
func (*ReporterBleRequest) ProtoMessage()    {}
func (*ReporterBleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{3}
}

func (m *ReporterBleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReporterBleRequest.Unmarshal(m, b)
}
func (m *ReporterBleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReporterBleRequest.Marshal(b, m, deterministic)
}
func (m *ReporterBleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterBleRequest.Merge(m, src)
}
func (m *ReporterBleRequest) XXX_Size() int {
	return xxx_messageInfo_ReporterBleRequest.Size(m)
}
func (m *ReporterBleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterBleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterBleRequest proto.InternalMessageInfo

func (m *ReporterBleRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *ReporterBleRequest) GetBles() *BleRequest {
	if m != nil {
		return m.Bles
	}
	return nil
}

func (m *ReporterBleRequest) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Agent struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{4}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Metadata struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{5}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Metadata) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DevicesResponse struct {
	Devices              []*Devices `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DevicesResponse) Reset()         { *m = DevicesResponse{} }
func (m *DevicesResponse) String() string { return proto.CompactTextString(m) }
func (*DevicesResponse) ProtoMessage()    {}
func (*DevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{6}
}

func (m *DevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesResponse.Unmarshal(m, b)
}
func (m *DevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesResponse.Marshal(b, m, deterministic)
}
func (m *DevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesResponse.Merge(m, src)
}
func (m *DevicesResponse) XXX_Size() int {
	return xxx_messageInfo_DevicesResponse.Size(m)
}
func (m *DevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesResponse proto.InternalMessageInfo

func (m *DevicesResponse) GetDevices() []*Devices {
	if m != nil {
		return m.Devices
	}
	return nil
}

type BleDevices struct {
	Id                   string      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LastSeen             int64       `protobuf:"varint,2,opt,name=LastSeen,proto3" json:"LastSeen,omitempty"`
	Commands             []*Commands `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	Name                 string      `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Home                 string      `protobuf:"bytes,5,opt,name=Home,proto3" json:"Home,omitempty"`
	Tile                 bool        `protobuf:"varint,6,opt,name=tile,proto3" json:"tile,omitempty"`
	Distance             float32     `protobuf:"fixed32,7,opt,name=distance,proto3" json:"distance,omitempty"`
	Metadata             []*Metadata `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Parent               string      `protobuf:"bytes,9,opt,name=Parent,proto3" json:"Parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BleDevices) Reset()         { *m = BleDevices{} }
func (m *BleDevices) String() string { return proto.CompactTextString(m) }
func (*BleDevices) ProtoMessage()    {}
func (*BleDevices) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{7}
}

func (m *BleDevices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BleDevices.Unmarshal(m, b)
}
func (m *BleDevices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BleDevices.Marshal(b, m, deterministic)
}
func (m *BleDevices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BleDevices.Merge(m, src)
}
func (m *BleDevices) XXX_Size() int {
	return xxx_messageInfo_BleDevices.Size(m)
}
func (m *BleDevices) XXX_DiscardUnknown() {
	xxx_messageInfo_BleDevices.DiscardUnknown(m)
}

var xxx_messageInfo_BleDevices proto.InternalMessageInfo

func (m *BleDevices) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BleDevices) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *BleDevices) GetCommands() []*Commands {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *BleDevices) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BleDevices) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *BleDevices) GetTile() bool {
	if m != nil {
		return m.Tile
	}
	return false
}

func (m *BleDevices) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *BleDevices) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BleDevices) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type Binding struct {
	DeviceMac            string   `protobuf:"bytes,1,opt,name=deviceMac,proto3" json:"deviceMac,omitempty"`
	BleMac               string   `protobuf:"bytes,2,opt,name=bleMac,proto3" json:"bleMac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Binding) Reset()         { *m = Binding{} }
func (m *Binding) String() string { return proto.CompactTextString(m) }
func (*Binding) ProtoMessage()    {}
func (*Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{8}
}

func (m *Binding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binding.Unmarshal(m, b)
}
func (m *Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binding.Marshal(b, m, deterministic)
}
func (m *Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binding.Merge(m, src)
}
func (m *Binding) XXX_Size() int {
	return xxx_messageInfo_Binding.Size(m)
}
func (m *Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_Binding proto.InternalMessageInfo

func (m *Binding) GetDeviceMac() string {
	if m != nil {
		return m.DeviceMac
	}
	return ""
}

func (m *Binding) GetBleMac() string {
	if m != nil {
		return m.BleMac
	}
	return ""
}

type Commands struct {
	Timeout              int64    `protobuf:"varint,1,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commands) Reset()         { *m = Commands{} }
func (m *Commands) String() string { return proto.CompactTextString(m) }
func (*Commands) ProtoMessage()    {}
func (*Commands) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{9}
}

func (m *Commands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commands.Unmarshal(m, b)
}
func (m *Commands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commands.Marshal(b, m, deterministic)
}
func (m *Commands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commands.Merge(m, src)
}
func (m *Commands) XXX_Size() int {
	return xxx_messageInfo_Commands.Size(m)
}
func (m *Commands) XXX_DiscardUnknown() {
	xxx_messageInfo_Commands.DiscardUnknown(m)
}

var xxx_messageInfo_Commands proto.InternalMessageInfo

func (m *Commands) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Commands) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Commands) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message containing the user's name.
type AddressRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac                  string   `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Distance             float32  `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Hosts                []string `protobuf:"bytes,4,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Vendor               string   `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{10}
}

func (m *AddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressRequest.Unmarshal(m, b)
}
func (m *AddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressRequest.Marshal(b, m, deterministic)
}
func (m *AddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressRequest.Merge(m, src)
}
func (m *AddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddressRequest.Size(m)
}
func (m *AddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressRequest proto.InternalMessageInfo

func (m *AddressRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddressRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *AddressRequest) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *AddressRequest) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *AddressRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

type AddressesRequest struct {
	Addresses            []*AddressRequest `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddressesRequest) Reset()         { *m = AddressesRequest{} }
func (m *AddressesRequest) String() string { return proto.CompactTextString(m) }
func (*AddressesRequest) ProtoMessage()    {}
func (*AddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{11}
}

func (m *AddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressesRequest.Unmarshal(m, b)
}
func (m *AddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressesRequest.Marshal(b, m, deterministic)
}
func (m *AddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressesRequest.Merge(m, src)
}
func (m *AddressesRequest) XXX_Size() int {
	return xxx_messageInfo_AddressesRequest.Size(m)
}
func (m *AddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressesRequest proto.InternalMessageInfo

func (m *AddressesRequest) GetAddresses() []*AddressRequest {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// The response message containing the greetings
type Reply struct {
	Acknowledged         bool     `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{12}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

type PeopleResponse struct {
	People               []*People `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PeopleResponse) Reset()         { *m = PeopleResponse{} }
func (m *PeopleResponse) String() string { return proto.CompactTextString(m) }
func (*PeopleResponse) ProtoMessage()    {}
func (*PeopleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{13}
}

func (m *PeopleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleResponse.Unmarshal(m, b)
}
func (m *PeopleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleResponse.Marshal(b, m, deterministic)
}
func (m *PeopleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleResponse.Merge(m, src)
}
func (m *PeopleResponse) XXX_Size() int {
	return xxx_messageInfo_PeopleResponse.Size(m)
}
func (m *PeopleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleResponse proto.InternalMessageInfo

func (m *PeopleResponse) GetPeople() []*People {
	if m != nil {
		return m.People
	}
	return nil
}

type People struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Ids                  []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Away                 bool     `protobuf:"varint,3,opt,name=away,proto3" json:"away,omitempty"`
	Home                 string   `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	LastSeen             int64    `protobuf:"varint,5,opt,name=LastSeen,proto3" json:"LastSeen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *People) Reset()         { *m = People{} }
func (m *People) String() string { return proto.CompactTextString(m) }
func (*People) ProtoMessage()    {}
func (*People) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{14}
}

func (m *People) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_People.Unmarshal(m, b)
}
func (m *People) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_People.Marshal(b, m, deterministic)
}
func (m *People) XXX_Merge(src proto.Message) {
	xxx_messageInfo_People.Merge(m, src)
}
func (m *People) XXX_Size() int {
	return xxx_messageInfo_People.Size(m)
}
func (m *People) XXX_DiscardUnknown() {
	xxx_messageInfo_People.DiscardUnknown(m)
}

var xxx_messageInfo_People proto.InternalMessageInfo

func (m *People) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *People) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *People) GetAway() bool {
	if m != nil {
		return m.Away
	}
	return false
}

func (m *People) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *People) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

type Devices struct {
	Id                   *NetworkId  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Home                 string      `protobuf:"bytes,2,opt,name=Home,proto3" json:"Home,omitempty"`
	LastSeen             int64       `protobuf:"varint,3,opt,name=LastSeen,proto3" json:"LastSeen,omitempty"`
	Away                 bool        `protobuf:"varint,4,opt,name=Away,proto3" json:"Away,omitempty"`
	Name                 string      `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Person               bool        `protobuf:"varint,6,opt,name=Person,proto3" json:"Person,omitempty"`
	Command              string      `protobuf:"bytes,7,opt,name=Command,proto3" json:"Command,omitempty"`
	Smart                bool        `protobuf:"varint,8,opt,name=Smart,proto3" json:"Smart,omitempty"`
	Manufacturer         string      `protobuf:"bytes,9,opt,name=Manufacturer,proto3" json:"Manufacturer,omitempty"`
	PresenceAware        bool        `protobuf:"varint,10,opt,name=PresenceAware,proto3" json:"PresenceAware,omitempty"`
	Latency              float32     `protobuf:"fixed32,11,opt,name=Latency,proto3" json:"Latency,omitempty"`
	Hostnames            []string    `protobuf:"bytes,12,rep,name=Hostnames,proto3" json:"Hostnames,omitempty"`
	Metadata             []*Metadata `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Devices) Reset()         { *m = Devices{} }
func (m *Devices) String() string { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()    {}
func (*Devices) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{15}
}

func (m *Devices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices.Unmarshal(m, b)
}
func (m *Devices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices.Marshal(b, m, deterministic)
}
func (m *Devices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices.Merge(m, src)
}
func (m *Devices) XXX_Size() int {
	return xxx_messageInfo_Devices.Size(m)
}
func (m *Devices) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices.DiscardUnknown(m)
}

var xxx_messageInfo_Devices proto.InternalMessageInfo

func (m *Devices) GetId() *NetworkId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Devices) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *Devices) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Devices) GetAway() bool {
	if m != nil {
		return m.Away
	}
	return false
}

func (m *Devices) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Devices) GetPerson() bool {
	if m != nil {
		return m.Person
	}
	return false
}

func (m *Devices) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Devices) GetSmart() bool {
	if m != nil {
		return m.Smart
	}
	return false
}

func (m *Devices) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Devices) GetPresenceAware() bool {
	if m != nil {
		return m.PresenceAware
	}
	return false
}

func (m *Devices) GetLatency() float32 {
	if m != nil {
		return m.Latency
	}
	return 0
}

func (m *Devices) GetHostnames() []string {
	if m != nil {
		return m.Hostnames
	}
	return nil
}

func (m *Devices) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type NetworkId struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Mac                  string   `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	UUID                 string   `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkId) Reset()         { *m = NetworkId{} }
func (m *NetworkId) String() string { return proto.CompactTextString(m) }
func (*NetworkId) ProtoMessage()    {}
func (*NetworkId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef78dd0228c0408, []int{16}
}

func (m *NetworkId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkId.Unmarshal(m, b)
}
func (m *NetworkId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkId.Marshal(b, m, deterministic)
}
func (m *NetworkId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkId.Merge(m, src)
}
func (m *NetworkId) XXX_Size() int {
	return xxx_messageInfo_NetworkId.Size(m)
}
func (m *NetworkId) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkId.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkId proto.InternalMessageInfo

func (m *NetworkId) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetworkId) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *NetworkId) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*StringRequest)(nil), "devicepb.StringRequest")
	proto.RegisterType((*BleRequest)(nil), "devicepb.BleRequest")
	proto.RegisterType((*ReporterAddressRequest)(nil), "devicepb.ReporterAddressRequest")
	proto.RegisterType((*ReporterBleRequest)(nil), "devicepb.ReporterBleRequest")
	proto.RegisterType((*Agent)(nil), "devicepb.Agent")
	proto.RegisterType((*Metadata)(nil), "devicepb.Metadata")
	proto.RegisterType((*DevicesResponse)(nil), "devicepb.DevicesResponse")
	proto.RegisterType((*BleDevices)(nil), "devicepb.BleDevices")
	proto.RegisterType((*Binding)(nil), "devicepb.Binding")
	proto.RegisterType((*Commands)(nil), "devicepb.Commands")
	proto.RegisterType((*AddressRequest)(nil), "devicepb.AddressRequest")
	proto.RegisterType((*AddressesRequest)(nil), "devicepb.AddressesRequest")
	proto.RegisterType((*Reply)(nil), "devicepb.Reply")
	proto.RegisterType((*PeopleResponse)(nil), "devicepb.PeopleResponse")
	proto.RegisterType((*People)(nil), "devicepb.People")
	proto.RegisterType((*Devices)(nil), "devicepb.Devices")
	proto.RegisterType((*NetworkId)(nil), "devicepb.networkId")
}

func init() {
	proto.RegisterFile("device_detector.proto", fileDescriptor_3ef78dd0228c0408)
}

var fileDescriptor_3ef78dd0228c0408 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4b, 0x6f, 0x23, 0x45,
	0x10, 0x5e, 0x7b, 0xfc, 0x18, 0x97, 0x93, 0x6c, 0x68, 0x42, 0x18, 0x0c, 0x87, 0x30, 0x80, 0x64,
	0x69, 0x25, 0xaf, 0x64, 0xd0, 0x0a, 0xed, 0x01, 0x70, 0x08, 0x52, 0x8c, 0x92, 0x55, 0xd4, 0xd9,
	0x70, 0xe0, 0x82, 0xda, 0x33, 0xb5, 0xce, 0x28, 0xf3, 0x62, 0xba, 0x9d, 0xc8, 0x12, 0x07, 0x8e,
	0xfc, 0x01, 0x6e, 0xfc, 0x1d, 0xfe, 0x17, 0xea, 0xd7, 0x3c, 0x62, 0x07, 0xcc, 0xad, 0xab, 0xba,
	0xaa, 0xeb, 0xeb, 0xaa, 0xef, 0x9b, 0x1e, 0xf8, 0x20, 0xc4, 0xfb, 0x28, 0xc0, 0x5f, 0x42, 0x14,
	0x18, 0x88, 0xac, 0x98, 0xe4, 0x45, 0x26, 0x32, 0xe2, 0x6a, 0x77, 0xbe, 0x18, 0x7d, 0xbc, 0xcc,
	0xb2, 0x65, 0x8c, 0x2f, 0x95, 0x7f, 0xb1, 0x7a, 0xf7, 0x12, 0x93, 0x5c, 0xac, 0x75, 0x98, 0xff,
	0x29, 0xec, 0x5f, 0x8b, 0x22, 0x4a, 0x97, 0x14, 0x7f, 0x5d, 0x21, 0x17, 0xe4, 0x10, 0x9c, 0x3b,
	0x5c, 0x7b, 0xad, 0x93, 0xd6, 0x78, 0x40, 0xe5, 0xd2, 0xff, 0x09, 0xe0, 0x34, 0xc6, 0x27, 0xf7,
	0xc9, 0x08, 0xdc, 0x30, 0xe2, 0x82, 0xa5, 0x01, 0x7a, 0xed, 0x93, 0xd6, 0xb8, 0x4d, 0x4b, 0x5b,
	0xee, 0xdd, 0x66, 0x5c, 0xa4, 0x2c, 0x41, 0xcf, 0x51, 0x29, 0xa5, 0xed, 0xff, 0xdd, 0x82, 0x63,
	0x8a, 0x79, 0x56, 0x08, 0x2c, 0x66, 0x61, 0x58, 0x20, 0xe7, 0xb6, 0xc8, 0x17, 0xd0, 0x65, 0x4b,
	0x4c, 0x85, 0x2a, 0x33, 0x9c, 0x3e, 0x9f, 0xd8, 0xcb, 0x4c, 0x66, 0xd2, 0x4d, 0xf5, 0x2e, 0x79,
	0x05, 0x03, 0xa6, 0x13, 0x91, 0x7b, 0xed, 0x13, 0x67, 0x3c, 0x9c, 0x7a, 0xb5, 0xd0, 0xc6, 0x99,
	0xb4, 0x0a, 0x25, 0x9f, 0xc0, 0x40, 0x44, 0x09, 0x72, 0xc1, 0x92, 0x5c, 0xc1, 0x72, 0x68, 0xe5,
	0x20, 0x13, 0x70, 0x13, 0x14, 0x2c, 0x64, 0x82, 0x79, 0x1d, 0x75, 0x28, 0xa9, 0x0e, 0xbd, 0x34,
	0x3b, 0xb4, 0x8c, 0xf1, 0xff, 0x6c, 0x01, 0xb1, 0xf7, 0xa8, 0x35, 0x6a, 0xc7, 0x3b, 0x8c, 0xa1,
	0xb3, 0x88, 0x15, 0x7c, 0x19, 0x75, 0x54, 0x45, 0x55, 0x47, 0x51, 0x15, 0xd1, 0xc0, 0xe5, 0xec,
	0x80, 0xeb, 0x05, 0x74, 0x55, 0x25, 0x42, 0xa0, 0x73, 0x9b, 0x25, 0x68, 0x66, 0xa6, 0xd6, 0xe4,
	0x00, 0xda, 0x51, 0xa8, 0x8a, 0x0e, 0x68, 0x3b, 0x0a, 0xfd, 0x29, 0xb8, 0xf6, 0x88, 0x2d, 0x23,
	0x3e, 0x82, 0xee, 0x3d, 0x8b, 0x57, 0x68, 0x12, 0xb4, 0xe1, 0x7f, 0x03, 0xcf, 0xcf, 0x54, 0x7d,
	0x4e, 0x91, 0xe7, 0x59, 0xca, 0x91, 0xbc, 0x80, 0xbe, 0x86, 0xc4, 0xbd, 0x96, 0x82, 0xf8, 0x5e,
	0x05, 0xd1, 0xc6, 0xda, 0x08, 0xff, 0x8f, 0xb6, 0x62, 0x96, 0xf1, 0x4b, 0x48, 0xf3, 0xd0, 0x54,
	0x6d, 0xcf, 0x43, 0xc9, 0x9d, 0x0b, 0xc6, 0xc5, 0x35, 0x62, 0xaa, 0xea, 0x3a, 0xb4, 0xb4, 0x65,
	0x2f, 0x82, 0x2c, 0x49, 0x58, 0x1a, 0xf2, 0xcd, 0x5e, 0x7c, 0x6f, 0x76, 0x68, 0x19, 0x23, 0x5b,
	0xf0, 0x46, 0x72, 0xb0, 0xa3, 0x5b, 0x20, 0xd7, 0xd2, 0x77, 0x2e, 0xdb, 0xd2, 0xd5, 0x3e, 0xb9,
	0x96, 0x3e, 0x11, 0xc5, 0xe8, 0xf5, 0x4e, 0x5a, 0x63, 0x97, 0xaa, 0x75, 0x83, 0xdf, 0xfd, 0x47,
	0xfc, 0xae, 0xcf, 0xc4, 0xfd, 0xef, 0x99, 0x90, 0x63, 0xe8, 0x5d, 0xb1, 0x42, 0xb2, 0x62, 0xa0,
	0xaa, 0x1a, 0xcb, 0xff, 0x16, 0xfa, 0xa7, 0x51, 0x1a, 0x46, 0xe9, 0x52, 0x92, 0x53, 0x9f, 0x70,
	0xc9, 0x02, 0xd3, 0x8d, 0xca, 0x21, 0x0f, 0x58, 0xc4, 0x6a, 0x4b, 0x8f, 0xc2, 0x58, 0xfe, 0x1b,
	0x70, 0xed, 0xb5, 0x89, 0x07, 0xfd, 0xb7, 0x51, 0x82, 0xd9, 0x4a, 0x73, 0xcf, 0xa1, 0xd6, 0x94,
	0x3b, 0x26, 0xca, 0xa4, 0x5b, 0xd3, 0x34, 0xdf, 0xb1, 0xcd, 0xf7, 0x7f, 0x83, 0x83, 0x47, 0x9a,
	0x94, 0x8c, 0xc9, 0xed, 0x78, 0xa2, 0x5c, 0xb2, 0x24, 0x29, 0x61, 0xc8, 0x65, 0xa3, 0x51, 0xce,
	0xa3, 0x46, 0x1d, 0x41, 0x57, 0x0a, 0x9f, 0x2b, 0x45, 0x0d, 0xa8, 0x36, 0xe4, 0x6d, 0xee, 0x31,
	0x0d, 0xb3, 0xc2, 0x0c, 0xc1, 0x58, 0xfe, 0x8f, 0x70, 0x38, 0xb3, 0x6a, 0xb5, 0xf5, 0x1b, 0x62,
	0x6f, 0xed, 0x2c, 0x76, 0x29, 0x03, 0x8a, 0x79, 0xbc, 0x26, 0x3e, 0xec, 0xb1, 0xe0, 0x2e, 0xcd,
	0x1e, 0x62, 0x0c, 0x97, 0xa8, 0x99, 0xe6, 0xd2, 0x86, 0xcf, 0x7f, 0x0d, 0x07, 0x57, 0x98, 0xe5,
	0x52, 0x7a, 0x86, 0xd1, 0x63, 0xe8, 0xe5, 0xca, 0x63, 0x6a, 0x1e, 0x56, 0x35, 0x4d, 0xa4, 0xd9,
	0xf7, 0x0b, 0xe8, 0x69, 0x4f, 0xc9, 0xb6, 0x56, 0x8d, 0x6d, 0x87, 0xe0, 0x44, 0xa1, 0xfe, 0x4a,
	0x0d, 0xa8, 0x5c, 0xca, 0x28, 0xf6, 0xc0, 0xd6, 0xaa, 0x55, 0x2e, 0x55, 0xeb, 0x52, 0xaa, 0x9d,
	0x9a, 0x54, 0xeb, 0x3a, 0xe8, 0x36, 0x75, 0xe0, 0xff, 0xee, 0x40, 0xdf, 0xea, 0xe7, 0xb3, 0x52,
	0x3f, 0xc3, 0xe9, 0xfb, 0x15, 0xca, 0x14, 0xc5, 0x43, 0x56, 0xdc, 0xcd, 0x43, 0x25, 0x2a, 0x4b,
	0xfa, 0x76, 0x8d, 0xf4, 0xf5, 0x02, 0xce, 0x23, 0xa1, 0x11, 0xe8, 0xcc, 0x24, 0xc8, 0x8e, 0x06,
	0x39, 0x33, 0x20, 0xd5, 0xf5, 0xba, 0xb5, 0xeb, 0x49, 0x62, 0x63, 0xc1, 0xb3, 0xd4, 0x48, 0xc7,
	0x58, 0x75, 0xc6, 0xf5, 0x9b, 0x8c, 0x3b, 0x82, 0xee, 0x75, 0xc2, 0x0a, 0xe1, 0xb9, 0x2a, 0x41,
	0x1b, 0x72, 0x48, 0x97, 0x2c, 0x5d, 0xbd, 0x63, 0x81, 0x58, 0x15, 0x58, 0x18, 0x99, 0x34, 0x7c,
	0xe4, 0x73, 0xd8, 0xbf, 0x2a, 0x90, 0x63, 0x1a, 0xe0, 0xec, 0x81, 0x15, 0xe8, 0x81, 0x3a, 0xa1,
	0xe9, 0x94, 0x95, 0x2f, 0x98, 0xc0, 0x34, 0x58, 0x7b, 0x43, 0x45, 0x46, 0x6b, 0x4a, 0x85, 0x9d,
	0x9b, 0x47, 0x88, 0x7b, 0x7b, 0x6a, 0x20, 0x95, 0xa3, 0x21, 0xe9, 0xfd, 0x1d, 0x3e, 0xb3, 0x33,
	0x18, 0x94, 0x2d, 0x56, 0x32, 0x2a, 0x45, 0x32, 0x57, 0x22, 0xa9, 0xb4, 0x2a, 0x97, 0xb2, 0x79,
	0x37, 0x37, 0xf3, 0x33, 0x23, 0x35, 0xb5, 0x9e, 0xfe, 0xd5, 0x81, 0x03, 0x3d, 0xc5, 0x33, 0xf3,
	0x88, 0x93, 0x09, 0x38, 0xb3, 0xe0, 0x8e, 0x6c, 0x7d, 0x0f, 0x46, 0xb5, 0xb7, 0x44, 0x51, 0xdb,
	0x7f, 0x46, 0x5e, 0x41, 0xdf, 0x48, 0x80, 0x3c, 0xa9, 0x8a, 0x6d, 0x79, 0xaf, 0x61, 0x50, 0x2a,
	0x8d, 0x8c, 0x36, 0x32, 0xf1, 0xdf, 0x72, 0x4f, 0x61, 0x78, 0x11, 0x71, 0x61, 0xf9, 0x77, 0x3c,
	0xd1, 0x3f, 0x1a, 0x13, 0xfb, 0xa3, 0x31, 0xf9, 0x41, 0xfe, 0x68, 0x8c, 0x3e, 0xda, 0x7c, 0x02,
	0x8c, 0xb8, 0xfc, 0x67, 0xe4, 0x2b, 0xd8, 0xbb, 0xc9, 0x43, 0x26, 0xcc, 0x2b, 0x40, 0x36, 0xdf,
	0x8b, 0xed, 0xa8, 0xf7, 0xce, 0x30, 0xc6, 0x32, 0xeb, 0xc3, 0x2a, 0xa4, 0xf1, 0x37, 0xb3, 0x2d,
	0xf7, 0x3b, 0x00, 0x89, 0xda, 0x48, 0xf5, 0x29, 0xd0, 0xde, 0x86, 0xcc, 0x1b, 0x98, 0xdf, 0x66,
	0xcb, 0x65, 0x8c, 0x86, 0xe3, 0xbb, 0x61, 0xfe, 0x1a, 0xe0, 0x3c, 0x5b, 0x71, 0x54, 0xe7, 0xff,
	0x1f, 0xc4, 0xa7, 0xf0, 0x73, 0xf9, 0x33, 0xb7, 0xe8, 0x29, 0x9c, 0x5f, 0xfe, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xdd, 0x90, 0xa0, 0x49, 0xf6, 0x09, 0x00, 0x00,
}
