// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package devicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DeviceDetectorClient is the client API for DeviceDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceDetectorClient interface {
	// Sends a greeting
	Ack(ctx context.Context, in *BleRequest, opts ...grpc.CallOption) (*Reply, error)
	Address(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*Reply, error)
	Addresses(ctx context.Context, in *AddressesRequest, opts ...grpc.CallOption) (*Reply, error)
	ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DevicesResponse, error)
	UpdateDevice(ctx context.Context, in *Devices, opts ...grpc.CallOption) (*Reply, error)
	DeleteDevice(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*Reply, error)
	ListPeople(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PeopleResponse, error)
	TogglePerson(ctx context.Context, in *Devices, opts ...grpc.CallOption) (*Reply, error)
	HouseEmpty(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*Reply, error)
}

type deviceDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceDetectorClient(cc grpc.ClientConnInterface) DeviceDetectorClient {
	return &deviceDetectorClient{cc}
}

func (c *deviceDetectorClient) Ack(ctx context.Context, in *BleRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) Address(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/Address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) Addresses(ctx context.Context, in *AddressesRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/Addresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DevicesResponse, error) {
	out := new(DevicesResponse)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) UpdateDevice(ctx context.Context, in *Devices, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) DeleteDevice(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) ListPeople(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PeopleResponse, error) {
	out := new(PeopleResponse)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/ListPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) TogglePerson(ctx context.Context, in *Devices, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/TogglePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceDetectorClient) HouseEmpty(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceDetector/HouseEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceDetectorServer is the server API for DeviceDetector service.
// All implementations must embed UnimplementedDeviceDetectorServer
// for forward compatibility
type DeviceDetectorServer interface {
	// Sends a greeting
	Ack(context.Context, *BleRequest) (*Reply, error)
	Address(context.Context, *AddressRequest) (*Reply, error)
	Addresses(context.Context, *AddressesRequest) (*Reply, error)
	ListDevices(context.Context, *emptypb.Empty) (*DevicesResponse, error)
	UpdateDevice(context.Context, *Devices) (*Reply, error)
	DeleteDevice(context.Context, *StringRequest) (*Reply, error)
	ListPeople(context.Context, *emptypb.Empty) (*PeopleResponse, error)
	TogglePerson(context.Context, *Devices) (*Reply, error)
	HouseEmpty(context.Context, *StringRequest) (*Reply, error)
	mustEmbedUnimplementedDeviceDetectorServer()
}

// UnimplementedDeviceDetectorServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceDetectorServer struct {
}

func (UnimplementedDeviceDetectorServer) Ack(context.Context, *BleRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedDeviceDetectorServer) Address(context.Context, *AddressRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Address not implemented")
}
func (UnimplementedDeviceDetectorServer) Addresses(context.Context, *AddressesRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Addresses not implemented")
}
func (UnimplementedDeviceDetectorServer) ListDevices(context.Context, *emptypb.Empty) (*DevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceDetectorServer) UpdateDevice(context.Context, *Devices) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedDeviceDetectorServer) DeleteDevice(context.Context, *StringRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDeviceDetectorServer) ListPeople(context.Context, *emptypb.Empty) (*PeopleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeople not implemented")
}
func (UnimplementedDeviceDetectorServer) TogglePerson(context.Context, *Devices) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TogglePerson not implemented")
}
func (UnimplementedDeviceDetectorServer) HouseEmpty(context.Context, *StringRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HouseEmpty not implemented")
}
func (UnimplementedDeviceDetectorServer) mustEmbedUnimplementedDeviceDetectorServer() {}

// UnsafeDeviceDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceDetectorServer will
// result in compilation errors.
type UnsafeDeviceDetectorServer interface {
	mustEmbedUnimplementedDeviceDetectorServer()
}

func RegisterDeviceDetectorServer(s grpc.ServiceRegistrar, srv DeviceDetectorServer) {
	s.RegisterService(&_DeviceDetector_serviceDesc, srv)
}

func _DeviceDetector_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/Ack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).Ack(ctx, req.(*BleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).Address(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_Addresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).Addresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/Addresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).Addresses(ctx, req.(*AddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).ListDevices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Devices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).UpdateDevice(ctx, req.(*Devices))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).DeleteDevice(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_ListPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).ListPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/ListPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).ListPeople(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_TogglePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Devices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).TogglePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/TogglePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).TogglePerson(ctx, req.(*Devices))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceDetector_HouseEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDetectorServer).HouseEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceDetector/HouseEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDetectorServer).HouseEmpty(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceDetector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devicepb.DeviceDetector",
	HandlerType: (*DeviceDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ack",
			Handler:    _DeviceDetector_Ack_Handler,
		},
		{
			MethodName: "Address",
			Handler:    _DeviceDetector_Address_Handler,
		},
		{
			MethodName: "Addresses",
			Handler:    _DeviceDetector_Addresses_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceDetector_ListDevices_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DeviceDetector_UpdateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DeviceDetector_DeleteDevice_Handler,
		},
		{
			MethodName: "ListPeople",
			Handler:    _DeviceDetector_ListPeople_Handler,
		},
		{
			MethodName: "TogglePerson",
			Handler:    _DeviceDetector_TogglePerson_Handler,
		},
		{
			MethodName: "HouseEmpty",
			Handler:    _DeviceDetector_HouseEmpty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device_detector.proto",
}
