// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alarm.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HomeRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeRequest) Reset()         { *m = HomeRequest{} }
func (m *HomeRequest) String() string { return proto.CompactTextString(m) }
func (*HomeRequest) ProtoMessage()    {}
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{0}
}

func (m *HomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeRequest.Unmarshal(m, b)
}
func (m *HomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeRequest.Marshal(b, m, deterministic)
}
func (m *HomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeRequest.Merge(m, src)
}
func (m *HomeRequest) XXX_Size() int {
	return xxx_messageInfo_HomeRequest.Size(m)
}
func (m *HomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeRequest proto.InternalMessageInfo

func (m *HomeRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type HomesResponse struct {
	Homes                []string `protobuf:"bytes,1,rep,name=homes,proto3" json:"homes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomesResponse) Reset()         { *m = HomesResponse{} }
func (m *HomesResponse) String() string { return proto.CompactTextString(m) }
func (*HomesResponse) ProtoMessage()    {}
func (*HomesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{1}
}

func (m *HomesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomesResponse.Unmarshal(m, b)
}
func (m *HomesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomesResponse.Marshal(b, m, deterministic)
}
func (m *HomesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomesResponse.Merge(m, src)
}
func (m *HomesResponse) XXX_Size() int {
	return xxx_messageInfo_HomesResponse.Size(m)
}
func (m *HomesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HomesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HomesResponse proto.InternalMessageInfo

func (m *HomesResponse) GetHomes() []string {
	if m != nil {
		return m.Homes
	}
	return nil
}

type HomeBoolRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Value                bool     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeBoolRequest) Reset()         { *m = HomeBoolRequest{} }
func (m *HomeBoolRequest) String() string { return proto.CompactTextString(m) }
func (*HomeBoolRequest) ProtoMessage()    {}
func (*HomeBoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{2}
}

func (m *HomeBoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeBoolRequest.Unmarshal(m, b)
}
func (m *HomeBoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeBoolRequest.Marshal(b, m, deterministic)
}
func (m *HomeBoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeBoolRequest.Merge(m, src)
}
func (m *HomeBoolRequest) XXX_Size() int {
	return xxx_messageInfo_HomeBoolRequest.Size(m)
}
func (m *HomeBoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeBoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeBoolRequest proto.InternalMessageInfo

func (m *HomeBoolRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *HomeBoolRequest) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type HomeStringRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeStringRequest) Reset()         { *m = HomeStringRequest{} }
func (m *HomeStringRequest) String() string { return proto.CompactTextString(m) }
func (*HomeStringRequest) ProtoMessage()    {}
func (*HomeStringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{3}
}

func (m *HomeStringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeStringRequest.Unmarshal(m, b)
}
func (m *HomeStringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeStringRequest.Marshal(b, m, deterministic)
}
func (m *HomeStringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeStringRequest.Merge(m, src)
}
func (m *HomeStringRequest) XXX_Size() int {
	return xxx_messageInfo_HomeStringRequest.Size(m)
}
func (m *HomeStringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeStringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeStringRequest proto.InternalMessageInfo

func (m *HomeStringRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *HomeStringRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BoolResponse struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{4}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func (m *BoolResponse) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type StringResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResponse) Reset()         { *m = StringResponse{} }
func (m *StringResponse) String() string { return proto.CompactTextString(m) }
func (*StringResponse) ProtoMessage()    {}
func (*StringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a4142572412ce8e, []int{5}
}

func (m *StringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponse.Unmarshal(m, b)
}
func (m *StringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponse.Marshal(b, m, deterministic)
}
func (m *StringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponse.Merge(m, src)
}
func (m *StringResponse) XXX_Size() int {
	return xxx_messageInfo_StringResponse.Size(m)
}
func (m *StringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponse proto.InternalMessageInfo

func (m *StringResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*HomeRequest)(nil), "proto.HomeRequest")
	proto.RegisterType((*HomesResponse)(nil), "proto.HomesResponse")
	proto.RegisterType((*HomeBoolRequest)(nil), "proto.HomeBoolRequest")
	proto.RegisterType((*HomeStringRequest)(nil), "proto.HomeStringRequest")
	proto.RegisterType((*BoolResponse)(nil), "proto.BoolResponse")
	proto.RegisterType((*StringResponse)(nil), "proto.StringResponse")
}

func init() {
	proto.RegisterFile("alarm.proto", fileDescriptor_4a4142572412ce8e)
}

var fileDescriptor_4a4142572412ce8e = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xd1, 0x4b, 0xfa, 0x50,
	0x14, 0xc7, 0xd9, 0x4f, 0x37, 0xf5, 0xf8, 0xcb, 0xe8, 0x66, 0x32, 0xd6, 0x8b, 0x8d, 0x0a, 0x9f,
	0x26, 0x28, 0x42, 0x25, 0x41, 0x05, 0x31, 0x1f, 0x7a, 0x88, 0x8d, 0xfe, 0x80, 0x89, 0x27, 0x13,
	0x36, 0xef, 0xda, 0x3d, 0x0a, 0xfe, 0xe1, 0xbd, 0xc7, 0xdd, 0x75, 0x38, 0xc3, 0x85, 0xf6, 0xb4,
	0x9d, 0xbb, 0xf3, 0xb9, 0xdf, 0xef, 0xbe, 0xe7, 0x40, 0x3d, 0x08, 0x83, 0x24, 0x72, 0xe2, 0x84,
	0x13, 0x67, 0x7a, 0xfa, 0xb0, 0xce, 0xa7, 0x9c, 0x4f, 0x43, 0xec, 0xa6, 0xd5, 0x78, 0xf1, 0xde,
	0xc5, 0x28, 0xa6, 0x95, 0xea, 0xb1, 0x2f, 0xa0, 0x3e, 0xe2, 0x11, 0x7a, 0xf8, 0xb9, 0x40, 0x41,
	0x8c, 0x41, 0xf9, 0x83, 0x47, 0x68, 0x6a, 0x6d, 0xad, 0x53, 0xf3, 0xd2, 0x77, 0xfb, 0x0a, 0x8e,
	0x64, 0x8b, 0xf0, 0x50, 0xc4, 0x7c, 0x2e, 0x90, 0x35, 0x41, 0x97, 0x1f, 0x84, 0xa9, 0xb5, 0x4b,
	0x9d, 0x9a, 0xa7, 0x0a, 0x7b, 0x08, 0xc7, 0xb2, 0xed, 0x89, 0xf3, 0xf0, 0x97, 0xdb, 0x24, 0xbc,
	0x0c, 0xc2, 0x05, 0x9a, 0xff, 0xda, 0x5a, 0xa7, 0xea, 0xa9, 0xc2, 0xbe, 0x87, 0x13, 0x09, 0xfb,
	0x94, 0xcc, 0xe6, 0xd3, 0xbd, 0xf1, 0x5a, 0x86, 0x5f, 0xc2, 0x7f, 0xa5, 0xbb, 0x71, 0xa8, 0xba,
	0xb4, 0xbc, 0xc8, 0x35, 0x34, 0x32, 0x81, 0x5d, 0x7d, 0xd9, 0x6d, 0xbd, 0xaf, 0x32, 0xe8, 0x8f,
	0x32, 0x47, 0xe6, 0x40, 0xc9, 0x45, 0x62, 0x4c, 0x85, 0xe5, 0xe4, 0x92, 0xb2, 0x4e, 0xd7, 0x67,
	0x5b, 0xba, 0x37, 0x60, 0xbc, 0xc5, 0x93, 0x80, 0x90, 0xb5, 0x72, 0x48, 0x2e, 0x12, 0xab, 0xe5,
	0xa8, 0x69, 0x38, 0xd9, 0x34, 0x9c, 0x67, 0x39, 0x0d, 0x36, 0x90, 0xa4, 0xc0, 0x84, 0x0a, 0xc9,
	0x9d, 0x82, 0x3d, 0xa8, 0xb8, 0x48, 0x23, 0x1e, 0x4e, 0xf6, 0x37, 0x79, 0x0b, 0x15, 0x7f, 0xcd,
	0x1c, 0xea, 0xf2, 0x01, 0x1a, 0x3e, 0x52, 0x9a, 0x8d, 0xbf, 0x12, 0x84, 0xd1, 0x1f, 0xfe, 0xb3,
	0xea, 0x22, 0xbd, 0xe0, 0x12, 0xc3, 0x9d, 0x8e, 0xcf, 0xd6, 0x67, 0x3f, 0x06, 0x35, 0x84, 0xaa,
	0x9f, 0x61, 0x66, 0x0e, 0xdb, 0x5a, 0x98, 0x22, 0x78, 0x00, 0x7a, 0xba, 0xc0, 0xac, 0xc0, 0x94,
	0xd5, 0xcc, 0xdd, 0xb8, 0x59, 0xf3, 0x3e, 0x18, 0x2e, 0xd2, 0xeb, 0x6c, 0x7e, 0x88, 0xd1, 0x3b,
	0x30, 0x7c, 0x05, 0x15, 0xdb, 0x2c, 0xb0, 0x31, 0x36, 0xd2, 0xba, 0xff, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x18, 0x5f, 0x0c, 0xc5, 0x03, 0x00, 0x00,
}
