// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package alarmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AlarmClient is the client API for Alarm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlarmClient interface {
	Get(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	Update(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Upsert(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	GetHold(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	SetHold(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetAlarmSystem(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLevel(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*StringResponse, error)
	SetLevel(ctx context.Context, in *HomeStringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	Homes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HomesResponse, error)
	GetPin(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*StringResponse, error)
	SetPin(ctx context.Context, in *HomeStringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type alarmClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmClient(cc grpc.ClientConnInterface) AlarmClient {
	return &alarmClient{cc}
}

func (c *alarmClient) Get(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) Update(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) Upsert(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) GetHold(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/GetHold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) SetHold(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/SetHold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) SetAlarmSystem(ctx context.Context, in *HomeBoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/SetAlarmSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) GetLevel(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/GetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) SetLevel(ctx context.Context, in *HomeStringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/SetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) Homes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HomesResponse, error) {
	out := new(HomesResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/Homes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) GetPin(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/GetPin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) SetPin(ctx context.Context, in *HomeStringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/alarmpb.Alarm/SetPin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServer is the server API for Alarm service.
// All implementations must embed UnimplementedAlarmServer
// for forward compatibility
type AlarmServer interface {
	Get(context.Context, *HomeRequest) (*BoolResponse, error)
	Update(context.Context, *HomeBoolRequest) (*emptypb.Empty, error)
	Upsert(context.Context, *HomeBoolRequest) (*BoolResponse, error)
	GetHold(context.Context, *HomeRequest) (*BoolResponse, error)
	SetHold(context.Context, *HomeBoolRequest) (*emptypb.Empty, error)
	SetAlarmSystem(context.Context, *HomeBoolRequest) (*emptypb.Empty, error)
	GetLevel(context.Context, *HomeRequest) (*StringResponse, error)
	SetLevel(context.Context, *HomeStringRequest) (*StringResponse, error)
	Homes(context.Context, *emptypb.Empty) (*HomesResponse, error)
	GetPin(context.Context, *HomeRequest) (*StringResponse, error)
	SetPin(context.Context, *HomeStringRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAlarmServer()
}

// UnimplementedAlarmServer must be embedded to have forward compatible implementations.
type UnimplementedAlarmServer struct {
}

func (UnimplementedAlarmServer) Get(context.Context, *HomeRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAlarmServer) Update(context.Context, *HomeBoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAlarmServer) Upsert(context.Context, *HomeBoolRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedAlarmServer) GetHold(context.Context, *HomeRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHold not implemented")
}
func (UnimplementedAlarmServer) SetHold(context.Context, *HomeBoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHold not implemented")
}
func (UnimplementedAlarmServer) SetAlarmSystem(context.Context, *HomeBoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAlarmSystem not implemented")
}
func (UnimplementedAlarmServer) GetLevel(context.Context, *HomeRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevel not implemented")
}
func (UnimplementedAlarmServer) SetLevel(context.Context, *HomeStringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLevel not implemented")
}
func (UnimplementedAlarmServer) Homes(context.Context, *emptypb.Empty) (*HomesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Homes not implemented")
}
func (UnimplementedAlarmServer) GetPin(context.Context, *HomeRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPin not implemented")
}
func (UnimplementedAlarmServer) SetPin(context.Context, *HomeStringRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPin not implemented")
}
func (UnimplementedAlarmServer) mustEmbedUnimplementedAlarmServer() {}

// UnsafeAlarmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlarmServer will
// result in compilation errors.
type UnsafeAlarmServer interface {
	mustEmbedUnimplementedAlarmServer()
}

func RegisterAlarmServer(s grpc.ServiceRegistrar, srv AlarmServer) {
	s.RegisterService(&_Alarm_serviceDesc, srv)
}

func _Alarm_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).Get(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).Update(ctx, req.(*HomeBoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).Upsert(ctx, req.(*HomeBoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_GetHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).GetHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/GetHold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).GetHold(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_SetHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).SetHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/SetHold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).SetHold(ctx, req.(*HomeBoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_SetAlarmSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).SetAlarmSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/SetAlarmSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).SetAlarmSystem(ctx, req.(*HomeBoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_GetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).GetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/GetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).GetLevel(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_SetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).SetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/SetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).SetLevel(ctx, req.(*HomeStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_Homes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).Homes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/Homes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).Homes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_GetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).GetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/GetPin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).GetPin(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_SetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).SetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarmpb.Alarm/SetPin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).SetPin(ctx, req.(*HomeStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alarm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alarmpb.Alarm",
	HandlerType: (*AlarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Alarm_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Alarm_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _Alarm_Upsert_Handler,
		},
		{
			MethodName: "GetHold",
			Handler:    _Alarm_GetHold_Handler,
		},
		{
			MethodName: "SetHold",
			Handler:    _Alarm_SetHold_Handler,
		},
		{
			MethodName: "SetAlarmSystem",
			Handler:    _Alarm_SetAlarmSystem_Handler,
		},
		{
			MethodName: "GetLevel",
			Handler:    _Alarm_GetLevel_Handler,
		},
		{
			MethodName: "SetLevel",
			Handler:    _Alarm_SetLevel_Handler,
		},
		{
			MethodName: "Homes",
			Handler:    _Alarm_Homes_Handler,
		},
		{
			MethodName: "GetPin",
			Handler:    _Alarm_GetPin_Handler,
		},
		{
			MethodName: "SetPin",
			Handler:    _Alarm_SetPin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarm.proto",
}
