// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package storepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreClient interface {
	GetNumberFromHome(ctx context.Context, in *GetNumberFromHomeRequest, opts ...grpc.CallOption) (*GetNumberFromHomeResponse, error)
	SetHome(ctx context.Context, in *SetHomeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error)
	IsEmpty(ctx context.Context, in *IsEmptyRequest, opts ...grpc.CallOption) (*IsEmptyResponse, error)
	SetAutoLights(ctx context.Context, in *SetAutoLightsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAutoLights(ctx context.Context, in *GetAutoLightsRequest, opts ...grpc.CallOption) (*GetAutoLightsResponse, error)
	GetCameras(ctx context.Context, in *GetCamerasRequest, opts ...grpc.CallOption) (*GetCamerasResponse, error)
	GetHomeOccupancy(ctx context.Context, in *GetHomeOccupancyRequest, opts ...grpc.CallOption) (*GetHomeOccupancyResponse, error)
	GetLastSeen(ctx context.Context, in *GetHomeOccupancyRequest, opts ...grpc.CallOption) (*GetLastSeenResponse, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) GetNumberFromHome(ctx context.Context, in *GetNumberFromHomeRequest, opts ...grpc.CallOption) (*GetNumberFromHomeResponse, error) {
	out := new(GetNumberFromHomeResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetNumberFromHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) SetHome(ctx context.Context, in *SetHomeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/store.Store/SetHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error) {
	out := new(GetHomeResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) IsEmpty(ctx context.Context, in *IsEmptyRequest, opts ...grpc.CallOption) (*IsEmptyResponse, error) {
	out := new(IsEmptyResponse)
	err := c.cc.Invoke(ctx, "/store.Store/IsEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) SetAutoLights(ctx context.Context, in *SetAutoLightsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/store.Store/SetAutoLights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetAutoLights(ctx context.Context, in *GetAutoLightsRequest, opts ...grpc.CallOption) (*GetAutoLightsResponse, error) {
	out := new(GetAutoLightsResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetAutoLights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetCameras(ctx context.Context, in *GetCamerasRequest, opts ...grpc.CallOption) (*GetCamerasResponse, error) {
	out := new(GetCamerasResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetCameras", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetHomeOccupancy(ctx context.Context, in *GetHomeOccupancyRequest, opts ...grpc.CallOption) (*GetHomeOccupancyResponse, error) {
	out := new(GetHomeOccupancyResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetHomeOccupancy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetLastSeen(ctx context.Context, in *GetHomeOccupancyRequest, opts ...grpc.CallOption) (*GetLastSeenResponse, error) {
	out := new(GetLastSeenResponse)
	err := c.cc.Invoke(ctx, "/store.Store/GetLastSeen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
// All implementations must embed UnimplementedStoreServer
// for forward compatibility
type StoreServer interface {
	GetNumberFromHome(context.Context, *GetNumberFromHomeRequest) (*GetNumberFromHomeResponse, error)
	SetHome(context.Context, *SetHomeRequest) (*emptypb.Empty, error)
	GetHome(context.Context, *GetHomeRequest) (*GetHomeResponse, error)
	IsEmpty(context.Context, *IsEmptyRequest) (*IsEmptyResponse, error)
	SetAutoLights(context.Context, *SetAutoLightsRequest) (*emptypb.Empty, error)
	GetAutoLights(context.Context, *GetAutoLightsRequest) (*GetAutoLightsResponse, error)
	GetCameras(context.Context, *GetCamerasRequest) (*GetCamerasResponse, error)
	GetHomeOccupancy(context.Context, *GetHomeOccupancyRequest) (*GetHomeOccupancyResponse, error)
	GetLastSeen(context.Context, *GetHomeOccupancyRequest) (*GetLastSeenResponse, error)
	mustEmbedUnimplementedStoreServer()
}

// UnimplementedStoreServer must be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (UnimplementedStoreServer) GetNumberFromHome(context.Context, *GetNumberFromHomeRequest) (*GetNumberFromHomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumberFromHome not implemented")
}
func (UnimplementedStoreServer) SetHome(context.Context, *SetHomeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHome not implemented")
}
func (UnimplementedStoreServer) GetHome(context.Context, *GetHomeRequest) (*GetHomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHome not implemented")
}
func (UnimplementedStoreServer) IsEmpty(context.Context, *IsEmptyRequest) (*IsEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEmpty not implemented")
}
func (UnimplementedStoreServer) SetAutoLights(context.Context, *SetAutoLightsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoLights not implemented")
}
func (UnimplementedStoreServer) GetAutoLights(context.Context, *GetAutoLightsRequest) (*GetAutoLightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAutoLights not implemented")
}
func (UnimplementedStoreServer) GetCameras(context.Context, *GetCamerasRequest) (*GetCamerasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCameras not implemented")
}
func (UnimplementedStoreServer) GetHomeOccupancy(context.Context, *GetHomeOccupancyRequest) (*GetHomeOccupancyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomeOccupancy not implemented")
}
func (UnimplementedStoreServer) GetLastSeen(context.Context, *GetHomeOccupancyRequest) (*GetLastSeenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastSeen not implemented")
}
func (UnimplementedStoreServer) mustEmbedUnimplementedStoreServer() {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_GetNumberFromHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumberFromHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetNumberFromHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetNumberFromHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetNumberFromHome(ctx, req.(*GetNumberFromHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_SetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).SetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/SetHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).SetHome(ctx, req.(*SetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetHome(ctx, req.(*GetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_IsEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).IsEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/IsEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).IsEmpty(ctx, req.(*IsEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_SetAutoLights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoLightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).SetAutoLights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/SetAutoLights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).SetAutoLights(ctx, req.(*SetAutoLightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetAutoLights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutoLightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetAutoLights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetAutoLights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetAutoLights(ctx, req.(*GetAutoLightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetCameras_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCamerasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetCameras(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetCameras",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetCameras(ctx, req.(*GetCamerasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetHomeOccupancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeOccupancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetHomeOccupancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetHomeOccupancy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetHomeOccupancy(ctx, req.(*GetHomeOccupancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetLastSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeOccupancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetLastSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetLastSeen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetLastSeen(ctx, req.(*GetHomeOccupancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumberFromHome",
			Handler:    _Store_GetNumberFromHome_Handler,
		},
		{
			MethodName: "SetHome",
			Handler:    _Store_SetHome_Handler,
		},
		{
			MethodName: "GetHome",
			Handler:    _Store_GetHome_Handler,
		},
		{
			MethodName: "IsEmpty",
			Handler:    _Store_IsEmpty_Handler,
		},
		{
			MethodName: "SetAutoLights",
			Handler:    _Store_SetAutoLights_Handler,
		},
		{
			MethodName: "GetAutoLights",
			Handler:    _Store_GetAutoLights_Handler,
		},
		{
			MethodName: "GetCameras",
			Handler:    _Store_GetCameras_Handler,
		},
		{
			MethodName: "GetHomeOccupancy",
			Handler:    _Store_GetHomeOccupancy_Handler,
		},
		{
			MethodName: "GetLastSeen",
			Handler:    _Store_GetLastSeen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
