// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package storepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNumberFromHomeRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumberFromHomeRequest) Reset()         { *m = GetNumberFromHomeRequest{} }
func (m *GetNumberFromHomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNumberFromHomeRequest) ProtoMessage()    {}
func (*GetNumberFromHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *GetNumberFromHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumberFromHomeRequest.Unmarshal(m, b)
}
func (m *GetNumberFromHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumberFromHomeRequest.Marshal(b, m, deterministic)
}
func (m *GetNumberFromHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumberFromHomeRequest.Merge(m, src)
}
func (m *GetNumberFromHomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNumberFromHomeRequest.Size(m)
}
func (m *GetNumberFromHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumberFromHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumberFromHomeRequest proto.InternalMessageInfo

func (m *GetNumberFromHomeRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *GetNumberFromHomeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetNumberFromHomeResponse struct {
	Numbers              []string `protobuf:"bytes,1,rep,name=numbers,proto3" json:"numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumberFromHomeResponse) Reset()         { *m = GetNumberFromHomeResponse{} }
func (m *GetNumberFromHomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetNumberFromHomeResponse) ProtoMessage()    {}
func (*GetNumberFromHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *GetNumberFromHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumberFromHomeResponse.Unmarshal(m, b)
}
func (m *GetNumberFromHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumberFromHomeResponse.Marshal(b, m, deterministic)
}
func (m *GetNumberFromHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumberFromHomeResponse.Merge(m, src)
}
func (m *GetNumberFromHomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetNumberFromHomeResponse.Size(m)
}
func (m *GetNumberFromHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumberFromHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumberFromHomeResponse proto.InternalMessageInfo

func (m *GetNumberFromHomeResponse) GetNumbers() []string {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type SetHomeRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Home                 string   `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHomeRequest) Reset()         { *m = SetHomeRequest{} }
func (m *SetHomeRequest) String() string { return proto.CompactTextString(m) }
func (*SetHomeRequest) ProtoMessage()    {}
func (*SetHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *SetHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHomeRequest.Unmarshal(m, b)
}
func (m *SetHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHomeRequest.Marshal(b, m, deterministic)
}
func (m *SetHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHomeRequest.Merge(m, src)
}
func (m *SetHomeRequest) XXX_Size() int {
	return xxx_messageInfo_SetHomeRequest.Size(m)
}
func (m *SetHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetHomeRequest proto.InternalMessageInfo

func (m *SetHomeRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *SetHomeRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *SetHomeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetHomeRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeRequest) Reset()         { *m = GetHomeRequest{} }
func (m *GetHomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetHomeRequest) ProtoMessage()    {}
func (*GetHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *GetHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeRequest.Unmarshal(m, b)
}
func (m *GetHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeRequest.Marshal(b, m, deterministic)
}
func (m *GetHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeRequest.Merge(m, src)
}
func (m *GetHomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetHomeRequest.Size(m)
}
func (m *GetHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeRequest proto.InternalMessageInfo

func (m *GetHomeRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *GetHomeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetHomeResponse struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeResponse) Reset()         { *m = GetHomeResponse{} }
func (m *GetHomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetHomeResponse) ProtoMessage()    {}
func (*GetHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *GetHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeResponse.Unmarshal(m, b)
}
func (m *GetHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeResponse.Marshal(b, m, deterministic)
}
func (m *GetHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeResponse.Merge(m, src)
}
func (m *GetHomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetHomeResponse.Size(m)
}
func (m *GetHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeResponse proto.InternalMessageInfo

func (m *GetHomeResponse) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type SetPinRequest struct {
	Domicile             string   `protobuf:"bytes,1,opt,name=domicile,proto3" json:"domicile,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPinRequest) Reset()         { *m = SetPinRequest{} }
func (m *SetPinRequest) String() string { return proto.CompactTextString(m) }
func (*SetPinRequest) ProtoMessage()    {}
func (*SetPinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *SetPinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPinRequest.Unmarshal(m, b)
}
func (m *SetPinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPinRequest.Marshal(b, m, deterministic)
}
func (m *SetPinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPinRequest.Merge(m, src)
}
func (m *SetPinRequest) XXX_Size() int {
	return xxx_messageInfo_SetPinRequest.Size(m)
}
func (m *SetPinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPinRequest proto.InternalMessageInfo

func (m *SetPinRequest) GetDomicile() string {
	if m != nil {
		return m.Domicile
	}
	return ""
}

func (m *SetPinRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetPinRequest struct {
	Domicile             string   `protobuf:"bytes,1,opt,name=domicile,proto3" json:"domicile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPinRequest) Reset()         { *m = GetPinRequest{} }
func (m *GetPinRequest) String() string { return proto.CompactTextString(m) }
func (*GetPinRequest) ProtoMessage()    {}
func (*GetPinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *GetPinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPinRequest.Unmarshal(m, b)
}
func (m *GetPinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPinRequest.Marshal(b, m, deterministic)
}
func (m *GetPinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPinRequest.Merge(m, src)
}
func (m *GetPinRequest) XXX_Size() int {
	return xxx_messageInfo_GetPinRequest.Size(m)
}
func (m *GetPinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPinRequest proto.InternalMessageInfo

func (m *GetPinRequest) GetDomicile() string {
	if m != nil {
		return m.Domicile
	}
	return ""
}

type GetPinResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPinResponse) Reset()         { *m = GetPinResponse{} }
func (m *GetPinResponse) String() string { return proto.CompactTextString(m) }
func (*GetPinResponse) ProtoMessage()    {}
func (*GetPinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *GetPinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPinResponse.Unmarshal(m, b)
}
func (m *GetPinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPinResponse.Marshal(b, m, deterministic)
}
func (m *GetPinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPinResponse.Merge(m, src)
}
func (m *GetPinResponse) XXX_Size() int {
	return xxx_messageInfo_GetPinResponse.Size(m)
}
func (m *GetPinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPinResponse proto.InternalMessageInfo

func (m *GetPinResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IsEmptyRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmptyRequest) Reset()         { *m = IsEmptyRequest{} }
func (m *IsEmptyRequest) String() string { return proto.CompactTextString(m) }
func (*IsEmptyRequest) ProtoMessage()    {}
func (*IsEmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *IsEmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmptyRequest.Unmarshal(m, b)
}
func (m *IsEmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmptyRequest.Marshal(b, m, deterministic)
}
func (m *IsEmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmptyRequest.Merge(m, src)
}
func (m *IsEmptyRequest) XXX_Size() int {
	return xxx_messageInfo_IsEmptyRequest.Size(m)
}
func (m *IsEmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmptyRequest proto.InternalMessageInfo

func (m *IsEmptyRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type IsEmptyResponse struct {
	IsEmpty              bool     `protobuf:"varint,1,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmptyResponse) Reset()         { *m = IsEmptyResponse{} }
func (m *IsEmptyResponse) String() string { return proto.CompactTextString(m) }
func (*IsEmptyResponse) ProtoMessage()    {}
func (*IsEmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{9}
}

func (m *IsEmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmptyResponse.Unmarshal(m, b)
}
func (m *IsEmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmptyResponse.Marshal(b, m, deterministic)
}
func (m *IsEmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmptyResponse.Merge(m, src)
}
func (m *IsEmptyResponse) XXX_Size() int {
	return xxx_messageInfo_IsEmptyResponse.Size(m)
}
func (m *IsEmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmptyResponse proto.InternalMessageInfo

func (m *IsEmptyResponse) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

type SetAutoLightsRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Auto                 bool     `protobuf:"varint,2,opt,name=auto,proto3" json:"auto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAutoLightsRequest) Reset()         { *m = SetAutoLightsRequest{} }
func (m *SetAutoLightsRequest) String() string { return proto.CompactTextString(m) }
func (*SetAutoLightsRequest) ProtoMessage()    {}
func (*SetAutoLightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{10}
}

func (m *SetAutoLightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAutoLightsRequest.Unmarshal(m, b)
}
func (m *SetAutoLightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAutoLightsRequest.Marshal(b, m, deterministic)
}
func (m *SetAutoLightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAutoLightsRequest.Merge(m, src)
}
func (m *SetAutoLightsRequest) XXX_Size() int {
	return xxx_messageInfo_SetAutoLightsRequest.Size(m)
}
func (m *SetAutoLightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAutoLightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAutoLightsRequest proto.InternalMessageInfo

func (m *SetAutoLightsRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *SetAutoLightsRequest) GetAuto() bool {
	if m != nil {
		return m.Auto
	}
	return false
}

type GetAutoLightsRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAutoLightsRequest) Reset()         { *m = GetAutoLightsRequest{} }
func (m *GetAutoLightsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAutoLightsRequest) ProtoMessage()    {}
func (*GetAutoLightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{11}
}

func (m *GetAutoLightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAutoLightsRequest.Unmarshal(m, b)
}
func (m *GetAutoLightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAutoLightsRequest.Marshal(b, m, deterministic)
}
func (m *GetAutoLightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAutoLightsRequest.Merge(m, src)
}
func (m *GetAutoLightsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAutoLightsRequest.Size(m)
}
func (m *GetAutoLightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAutoLightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAutoLightsRequest proto.InternalMessageInfo

func (m *GetAutoLightsRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type GetAutoLightsResponse struct {
	Auto                 bool     `protobuf:"varint,1,opt,name=auto,proto3" json:"auto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAutoLightsResponse) Reset()         { *m = GetAutoLightsResponse{} }
func (m *GetAutoLightsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAutoLightsResponse) ProtoMessage()    {}
func (*GetAutoLightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{12}
}

func (m *GetAutoLightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAutoLightsResponse.Unmarshal(m, b)
}
func (m *GetAutoLightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAutoLightsResponse.Marshal(b, m, deterministic)
}
func (m *GetAutoLightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAutoLightsResponse.Merge(m, src)
}
func (m *GetAutoLightsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAutoLightsResponse.Size(m)
}
func (m *GetAutoLightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAutoLightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAutoLightsResponse proto.InternalMessageInfo

func (m *GetAutoLightsResponse) GetAuto() bool {
	if m != nil {
		return m.Auto
	}
	return false
}

type GetCamerasRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCamerasRequest) Reset()         { *m = GetCamerasRequest{} }
func (m *GetCamerasRequest) String() string { return proto.CompactTextString(m) }
func (*GetCamerasRequest) ProtoMessage()    {}
func (*GetCamerasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{13}
}

func (m *GetCamerasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCamerasRequest.Unmarshal(m, b)
}
func (m *GetCamerasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCamerasRequest.Marshal(b, m, deterministic)
}
func (m *GetCamerasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCamerasRequest.Merge(m, src)
}
func (m *GetCamerasRequest) XXX_Size() int {
	return xxx_messageInfo_GetCamerasRequest.Size(m)
}
func (m *GetCamerasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCamerasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCamerasRequest proto.InternalMessageInfo

func (m *GetCamerasRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type GetCamerasResponse struct {
	Cameras              []string `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCamerasResponse) Reset()         { *m = GetCamerasResponse{} }
func (m *GetCamerasResponse) String() string { return proto.CompactTextString(m) }
func (*GetCamerasResponse) ProtoMessage()    {}
func (*GetCamerasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{14}
}

func (m *GetCamerasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCamerasResponse.Unmarshal(m, b)
}
func (m *GetCamerasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCamerasResponse.Marshal(b, m, deterministic)
}
func (m *GetCamerasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCamerasResponse.Merge(m, src)
}
func (m *GetCamerasResponse) XXX_Size() int {
	return xxx_messageInfo_GetCamerasResponse.Size(m)
}
func (m *GetCamerasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCamerasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCamerasResponse proto.InternalMessageInfo

func (m *GetCamerasResponse) GetCameras() []string {
	if m != nil {
		return m.Cameras
	}
	return nil
}

type GetHomeOccupancyRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeOccupancyRequest) Reset()         { *m = GetHomeOccupancyRequest{} }
func (m *GetHomeOccupancyRequest) String() string { return proto.CompactTextString(m) }
func (*GetHomeOccupancyRequest) ProtoMessage()    {}
func (*GetHomeOccupancyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{15}
}

func (m *GetHomeOccupancyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeOccupancyRequest.Unmarshal(m, b)
}
func (m *GetHomeOccupancyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeOccupancyRequest.Marshal(b, m, deterministic)
}
func (m *GetHomeOccupancyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeOccupancyRequest.Merge(m, src)
}
func (m *GetHomeOccupancyRequest) XXX_Size() int {
	return xxx_messageInfo_GetHomeOccupancyRequest.Size(m)
}
func (m *GetHomeOccupancyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeOccupancyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeOccupancyRequest proto.InternalMessageInfo

func (m *GetHomeOccupancyRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

type GetHomeOccupancyResponse struct {
	Occupants            []string `protobuf:"bytes,1,rep,name=occupants,proto3" json:"occupants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeOccupancyResponse) Reset()         { *m = GetHomeOccupancyResponse{} }
func (m *GetHomeOccupancyResponse) String() string { return proto.CompactTextString(m) }
func (*GetHomeOccupancyResponse) ProtoMessage()    {}
func (*GetHomeOccupancyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{16}
}

func (m *GetHomeOccupancyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeOccupancyResponse.Unmarshal(m, b)
}
func (m *GetHomeOccupancyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeOccupancyResponse.Marshal(b, m, deterministic)
}
func (m *GetHomeOccupancyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeOccupancyResponse.Merge(m, src)
}
func (m *GetHomeOccupancyResponse) XXX_Size() int {
	return xxx_messageInfo_GetHomeOccupancyResponse.Size(m)
}
func (m *GetHomeOccupancyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeOccupancyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeOccupancyResponse proto.InternalMessageInfo

func (m *GetHomeOccupancyResponse) GetOccupants() []string {
	if m != nil {
		return m.Occupants
	}
	return nil
}

type GetLastSeenResponse struct {
	Response             []*LastSeen `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetLastSeenResponse) Reset()         { *m = GetLastSeenResponse{} }
func (m *GetLastSeenResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastSeenResponse) ProtoMessage()    {}
func (*GetLastSeenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{17}
}

func (m *GetLastSeenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastSeenResponse.Unmarshal(m, b)
}
func (m *GetLastSeenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastSeenResponse.Marshal(b, m, deterministic)
}
func (m *GetLastSeenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastSeenResponse.Merge(m, src)
}
func (m *GetLastSeenResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastSeenResponse.Size(m)
}
func (m *GetLastSeenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastSeenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastSeenResponse proto.InternalMessageInfo

func (m *GetLastSeenResponse) GetResponse() []*LastSeen {
	if m != nil {
		return m.Response
	}
	return nil
}

type LastSeen struct {
	Lastseen             int64    `protobuf:"varint,1,opt,name=lastseen,proto3" json:"lastseen,omitempty"`
	Occupant             string   `protobuf:"bytes,2,opt,name=occupant,proto3" json:"occupant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastSeen) Reset()         { *m = LastSeen{} }
func (m *LastSeen) String() string { return proto.CompactTextString(m) }
func (*LastSeen) ProtoMessage()    {}
func (*LastSeen) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{18}
}

func (m *LastSeen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastSeen.Unmarshal(m, b)
}
func (m *LastSeen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastSeen.Marshal(b, m, deterministic)
}
func (m *LastSeen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastSeen.Merge(m, src)
}
func (m *LastSeen) XXX_Size() int {
	return xxx_messageInfo_LastSeen.Size(m)
}
func (m *LastSeen) XXX_DiscardUnknown() {
	xxx_messageInfo_LastSeen.DiscardUnknown(m)
}

var xxx_messageInfo_LastSeen proto.InternalMessageInfo

func (m *LastSeen) GetLastseen() int64 {
	if m != nil {
		return m.Lastseen
	}
	return 0
}

func (m *LastSeen) GetOccupant() string {
	if m != nil {
		return m.Occupant
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNumberFromHomeRequest)(nil), "store.GetNumberFromHomeRequest")
	proto.RegisterType((*GetNumberFromHomeResponse)(nil), "store.GetNumberFromHomeResponse")
	proto.RegisterType((*SetHomeRequest)(nil), "store.SetHomeRequest")
	proto.RegisterType((*GetHomeRequest)(nil), "store.GetHomeRequest")
	proto.RegisterType((*GetHomeResponse)(nil), "store.GetHomeResponse")
	proto.RegisterType((*SetPinRequest)(nil), "store.SetPinRequest")
	proto.RegisterType((*GetPinRequest)(nil), "store.GetPinRequest")
	proto.RegisterType((*GetPinResponse)(nil), "store.GetPinResponse")
	proto.RegisterType((*IsEmptyRequest)(nil), "store.IsEmptyRequest")
	proto.RegisterType((*IsEmptyResponse)(nil), "store.IsEmptyResponse")
	proto.RegisterType((*SetAutoLightsRequest)(nil), "store.SetAutoLightsRequest")
	proto.RegisterType((*GetAutoLightsRequest)(nil), "store.GetAutoLightsRequest")
	proto.RegisterType((*GetAutoLightsResponse)(nil), "store.GetAutoLightsResponse")
	proto.RegisterType((*GetCamerasRequest)(nil), "store.GetCamerasRequest")
	proto.RegisterType((*GetCamerasResponse)(nil), "store.GetCamerasResponse")
	proto.RegisterType((*GetHomeOccupancyRequest)(nil), "store.GetHomeOccupancyRequest")
	proto.RegisterType((*GetHomeOccupancyResponse)(nil), "store.GetHomeOccupancyResponse")
	proto.RegisterType((*GetLastSeenResponse)(nil), "store.GetLastSeenResponse")
	proto.RegisterType((*LastSeen)(nil), "store.LastSeen")
}

func init() {
	proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc)
}

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6f, 0xd3, 0x4c,
	0x10, 0x55, 0xda, 0x26, 0x71, 0x26, 0x6a, 0xf2, 0x7d, 0x4b, 0x1a, 0x1c, 0xb7, 0xa2, 0xd1, 0x8a,
	0x1f, 0x15, 0x01, 0x57, 0x2a, 0x42, 0xea, 0x09, 0x91, 0x00, 0x35, 0x45, 0x15, 0x20, 0x1b, 0x71,
	0xe0, 0x82, 0x1c, 0xb3, 0xa4, 0x96, 0xe2, 0x6c, 0xf0, 0xae, 0x91, 0xb8, 0xf2, 0x97, 0xa3, 0x8c,
	0xd7, 0xeb, 0xd8, 0x38, 0x21, 0xb7, 0x9d, 0x99, 0x37, 0x6f, 0x66, 0x67, 0xdf, 0x2c, 0xb4, 0x85,
	0xe4, 0x31, 0xb3, 0x97, 0x31, 0x97, 0x9c, 0xd4, 0xd1, 0xb0, 0x8e, 0x67, 0x9c, 0xcf, 0xe6, 0xec,
	0x1c, 0x9d, 0xd3, 0xe4, 0xfb, 0x39, 0x8b, 0x96, 0xf2, 0x57, 0x8a, 0xa1, 0x57, 0x60, 0x3a, 0x4c,
	0xbe, 0x4f, 0xa2, 0x29, 0x8b, 0xaf, 0x62, 0x1e, 0xbd, 0xe5, 0x11, 0x73, 0xd9, 0x8f, 0x84, 0x09,
	0x49, 0x08, 0x1c, 0xdc, 0xf2, 0x88, 0x99, 0xb5, 0x61, 0xed, 0xac, 0xe5, 0xe2, 0x99, 0xf4, 0xa1,
	0x21, 0x78, 0x12, 0x07, 0xcc, 0xdc, 0x43, 0xaf, 0xb2, 0xe8, 0x73, 0x18, 0x54, 0xf0, 0x88, 0x25,
	0x5f, 0x08, 0x46, 0x4c, 0x68, 0x2e, 0x30, 0x22, 0xcc, 0xda, 0x70, 0xff, 0xac, 0xe5, 0x66, 0x26,
	0xfd, 0x04, 0x1d, 0x8f, 0xc9, 0xf5, 0xa2, 0x7d, 0x68, 0xa4, 0x41, 0x55, 0x56, 0x59, 0xba, 0x99,
	0xbd, 0xca, 0x66, 0xf6, 0x0b, 0xcd, 0xbc, 0x84, 0x8e, 0xb3, 0x1b, 0xeb, 0xa6, 0xeb, 0x3c, 0x80,
	0xae, 0x66, 0x50, 0x97, 0xa8, 0x98, 0x06, 0x1d, 0xc3, 0xa1, 0xc7, 0xe4, 0xc7, 0x70, 0x91, 0xd5,
	0xb1, 0xc0, 0xf8, 0xc6, 0xa3, 0x30, 0x08, 0xe7, 0x19, 0x50, 0xdb, 0xa4, 0x07, 0xf5, 0x9f, 0xfe,
	0x3c, 0xc9, 0x4a, 0xa5, 0x06, 0x1d, 0xc1, 0xa1, 0xb3, 0x2b, 0x05, 0x7d, 0x88, 0x17, 0x43, 0xb0,
	0xea, 0x4a, 0x93, 0xd6, 0xd6, 0x49, 0xef, 0x43, 0xe7, 0x5a, 0xbc, 0x59, 0x3d, 0xf3, 0x96, 0xb7,
	0xa4, 0x4f, 0xa0, 0xab, 0x51, 0x8a, 0x6e, 0x00, 0x46, 0x28, 0xbe, 0xa2, 0x40, 0x10, 0x6a, 0xb8,
	0xcd, 0x30, 0x85, 0xd0, 0x17, 0xd0, 0xf3, 0x98, 0x1c, 0x27, 0x92, 0xdf, 0x84, 0xb3, 0x5b, 0x29,
	0xb6, 0xa9, 0x84, 0xc0, 0x81, 0x9f, 0x48, 0x8e, 0x37, 0x35, 0x5c, 0x3c, 0xd3, 0xc7, 0xd0, 0x73,
	0x76, 0xcc, 0xa7, 0x23, 0x38, 0x2a, 0x61, 0xf3, 0x47, 0x40, 0xe2, 0xda, 0x1a, 0xf1, 0x23, 0xf8,
	0xdf, 0x61, 0xf2, 0x95, 0x1f, 0xb1, 0xd8, 0xdf, 0xca, 0x6a, 0x03, 0x59, 0x07, 0xe6, 0xe2, 0x0c,
	0x52, 0x57, 0x26, 0x4e, 0x65, 0xd2, 0xa7, 0x70, 0x57, 0x89, 0xe0, 0x43, 0x10, 0x24, 0x4b, 0x7f,
	0x11, 0x6c, 0x1d, 0xe7, 0x25, 0xae, 0x52, 0x09, 0xae, 0x8a, 0x9c, 0x40, 0x8b, 0xa7, 0x4e, 0x99,
	0x95, 0xc9, 0x1d, 0x74, 0x02, 0x77, 0x1c, 0x26, 0x6f, 0x7c, 0x21, 0x3d, 0xc6, 0xf2, 0xb7, 0x1d,
	0x81, 0x11, 0xab, 0x33, 0xe6, 0xb4, 0x2f, 0xba, 0x76, 0xba, 0xdf, 0x1a, 0xaa, 0x01, 0x74, 0x02,
	0x46, 0xe6, 0x5d, 0x49, 0x68, 0xee, 0x0b, 0x29, 0x18, 0x5b, 0x60, 0x87, 0xfb, 0xae, 0xb6, 0x57,
	0xb1, 0xac, 0xb0, 0x12, 0xa2, 0xb6, 0x2f, 0x7e, 0xd7, 0xa1, 0xee, 0xad, 0x0a, 0x90, 0xcf, 0x38,
	0xd3, 0xe2, 0x3a, 0x93, 0x53, 0x55, 0x7d, 0xd3, 0x87, 0x61, 0x0d, 0x37, 0x03, 0xd4, 0x95, 0x2e,
	0xa1, 0xa9, 0xf6, 0x9d, 0x1c, 0x29, 0x70, 0x71, 0xff, 0xad, 0xbe, 0x9d, 0x7e, 0x57, 0x76, 0xf6,
	0x5d, 0xd9, 0x28, 0xbf, 0x55, 0xa6, 0x53, 0xca, 0x74, 0xca, 0x99, 0x25, 0x77, 0x5e, 0x53, 0xc9,
	0x5c, 0x67, 0x16, 0x97, 0x43, 0x67, 0x96, 0xb7, 0xe1, 0x35, 0xae, 0x77, 0x2e, 0x43, 0x72, 0x9c,
	0xf7, 0xfc, 0x97, 0x90, 0x37, 0x76, 0xfe, 0x0e, 0x37, 0xbc, 0x82, 0xa5, 0x6a, 0x1d, 0xac, 0x93,
	0xea, 0xa0, 0xea, 0x68, 0x0c, 0x90, 0x4b, 0x98, 0x98, 0x39, 0xb6, 0x28, 0x7f, 0x6b, 0x50, 0x11,
	0x51, 0x14, 0x1e, 0xfc, 0x57, 0x96, 0x29, 0xb9, 0x57, 0x1c, 0x5d, 0x59, 0xee, 0xd6, 0xe9, 0xc6,
	0xb8, 0x22, 0xbd, 0x86, 0xf6, 0x9a, 0x82, 0xff, 0xc9, 0x67, 0xe5, 0xf1, 0xb2, 0xea, 0x27, 0xad,
	0x2f, 0x4d, 0x0c, 0x2e, 0xa7, 0xd3, 0x06, 0x4e, 0xf2, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0xc6, 0x1f, 0x79, 0xd6, 0x06, 0x00, 0x00,
}
